= *USBSID-Player manual*
:author: LouD
:description: This document contains information about the embedded USBSID-Player and how to use it
:url-repo: https://www.github.com/LouDnl/USBSID-Pico
:revdate: {localdate}
:hide-uri-scheme:
:toc:
:toclevels: 4
:toc-placement!:

Author: {author} - generated on {revdate}

toc::[]
[%always]
<<<

== Disclaimer
include::disclaimer.adoc[]


== What!?
Yes you read that right, USBSID-Player is embedded on USBSID-Pico and allows you to play PSID, RSID, PRG or P00 chiptunes without the need of an emulator on your computer!


== Firmwares with embedded USBSID-Player
Starting with firmware version v0.6.0-BETA firmwares have an embedded emulator that can play PSID and RSID tunes and PSID64 PRG/P00 files. +
From v0.8.1 and later these files are for example `usbsidpico-v1.0_em.uf2`, `usbsidpico2-v1.3-rgb_em.uf2` or `usbsidpico2-v1.5_em.uf2` +
This USBSID-Player is in active development and some tunes might not work or play at all, let me know if you come across any! +
**NOTE!** Due to the hardware limitations of the RP2040, highly demanding, cycle-exact SID tunes (dense per-cycle register writes, e.g. some digi/sample tunes) may not play at full speed on Pico1 or Pico1_w boards. Use a Pico2 or Pico2_w (rp2350) board for these tunes. +
**WARNING!** Whenever the USBSID-Player is compiled into the firmware, the Pico MCU is overclocked to 250MHz, regardless of Pico type. Passive cooling _might/could_ be needed. +
Cynthcart also runs through the embedded USBSID-Player - see the `USBSID-Pico-Cynthcart-manual` file for more information. +


== Usage
To play SID tunes and run PRG/P00 PSID64 files _on_ USBSID-Pico you will need the `send_sid` tool that is available in the `tools.zip` starting with firmware release v0.6.0-BETA and up, the help menu is self explanatory. +
Firmware release v0.7.0 and up supports the send sid mode on the USBSID-Pico config website and on Deepsid! +
Multi-subtune PSID/RSID files are supported - you can switch to the next or previous subtune while a tune is playing.


== Development
More information about USBSID-Player is available on the https://github.com/LouDnl/USBSID-Player[github repo]


== License
include::license-software.adoc[]

include::license-hardware.adoc[]

Author: {author} - generated on {revdate}
